# Should be overwritten from Cargo.toml when run with cargo
edition = "2018"
format_strings = true
hard_tabs = true
imports_granularity = "Module"
newline_style = "Unix"
#reorder_impl_items = true
group_imports = "StdExternalCrate"

# report_fixme = "Always"
# report_todo = "Always"
