[package]
name = "punktf"
version = "0.1.0"
authors = ["Michael Lohr <michael@lohr.dev>", "Shemnei"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.0.0-beta.2"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"

[profile.dev]
opt-level = 0

[profile.release]
lto = "thin"
opt-level = 3
