cargo-features = ["strip"]

[package]
name = "punktf"
version = "1.0.1"
authors = ["Michael Lohr <michael@lohr.dev>", "Shemnei"]
edition = "2018"
description = "A cross-platform multi-target dotfiles manager"
documentation = "https://github.com/Shemnei/punktf"
homepage = "https://github.com/Shemnei/punktf"
repository = "https://github.com/Shemnei/punktf"
license= "MIT"
exclude = ["/package/", "/Makefile", "/.git/", "/.github/"]
keywords = ["dotfiles", "cli", "dotfile", "dotfiles-manager"]
categories = ["command-line-utilities", "config"]

[[bin]]
path = "crates/punktf-cli/main.rs"
name = "punktf"

[workspace]
members = [
	"crates/punktf-lib"
]

[dependencies]
clap = "3.0.0-beta.4"
color-eyre = { version = "0.5.11", default-features = false }
env_logger = { version = "0.9.0", default-features = false, features = ["termcolor", "atty"] }
log = "0.4.14"
punktf-lib = { version = "1.0.0", path = "crates/punktf-lib" }

[profile.dev]
opt-level = 0

[profile.dev.package.backtrace]
# color-eyre: Improves performance for debug builds
opt-level = 3

[profile.release]
lto = "thin"
opt-level = 3
# Strip symbols for the release build to decrease binary size
strip = true
# Reduces parallel code generation units to increase optimizations
codegen-units = 1
