cargo-features = ["strip"]

[package]
name = "punktf"
version = "1.0.0-alpha.1"
authors = ["Michael Lohr <michael@lohr.dev>", "Shemnei"]
edition = "2018"
description = "A cross-platform multi-target dotfiles manager"
documentation = "https://github.com/Shemnei/punktf"
homepage = "https://github.com/Shemnei/punktf"
repository = "https://github.com/Shemnei/punktf"
license= "MIT"
keywords = ["dotfiles", "cli", "dotfile", "dotfiles-manager"]
categories = ["command-line-utilities", "config"]

[[bin]]
path = "src/main.rs"
name = "punktf"

[dependencies]
clap = "3.0.0-beta.2"
color-eyre = "0.5.11"
env_logger = "0.9.0"
log = "0.4.14"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_yaml = "0.8.17"
thiserror = "1.0.26"
walkdir = "2.3.2"
unicode-width = "0.1.8"

[dev-dependencies]
pretty_assertions = "0.7.2"

[profile.dev]
opt-level = 0

[profile.release]
lto = "thin"
opt-level = 3
# Strip symbols for the release build to decrease binary size
strip = true
# Reduces parallel code generation units to increase optimizations
codegen-units = 1
