on:
  pull_request:
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
      - '.rustfmt.toml'
      - 'crates/**'
      - 'examples/**'
  push:
    branches:
      - main
      - staging
      - trying
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
      - '.rustfmt.toml'
      - 'crates/**'
      - 'examples/**'

name: punktf Examples CI

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W rust-2021-compatibility"
  RUSTUP_MAX_RETRIES: 10

jobs:
  examples:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # This plugin should be loaded after toolchain setup
      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path crates/punktf-cli

      - name: Check Examples
        run: |
          cd examples
          ./ci.sh
