# Template from here <https://github.com/rust-lang/book/blob/main/.github/workflows/main.yml>

name: mdBook CI

on:
  push:
    branches:
      - main
      - staging
      - trying
    paths:
      - 'guide/**'
  pull_request:
    paths:
      - 'guide/**'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rust-docs

      - name: Install mdbook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> "${GITHUB_PATH}"

      - name: Report versions
        run: |
          rustup --version
          rustc -Vv
          mdbook --version

      - name: Run tests
        run: |
          cd guide
          mdbook test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update rustup
        run: rustup self update

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rust-docs

      - name: Install mdbook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> "${GITHUB_PATH}"

      - name: Install aspell
        run: sudo apt-get install aspell

      - name: Report versions
        run: |
          rustup --version
          rustc -Vv
          mdbook --version
          aspell --version

      - name: Shellcheck
        run: find . -name '*.sh' -exec shellcheck {} \;

      - name: Spellcheck
        run: |
          cd guide
          bash ci/spellcheck.sh list

      - name: Build book
        run: |
          cd guide
          mdbook build

      - name: Check for broken links
        run: |
          cd guide
          curl -sSLo linkcheck.sh \
            https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
          # Cannot use --all here because of the generated redirect pages aren't available.
          sh linkcheck.sh book
