# Template from here <https://github.com/rust-lang/book/blob/main/.github/workflows/main.yml>

name: mdBook-CI
on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install mdbook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> ${GITHUB_PATH}
      - name: Report versions
        run: |
          mdbook --version
      - name: Run tests
        run: |
          cd guide
          mdbook test

  lint:
    name: Run lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install mdbook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> ${GITHUB_PATH}
      - name: Install aspell
        run: sudo apt-get install aspell
      - name: Report versions
        run: |
          mdbook --version
          aspell --version
      - name: Shellcheck
        run: find . -name '*.sh' | xargs shellcheck
      - name: Spellcheck
        run: |
          cd guide
          bash ci/spellcheck.sh list
      - name: Lint for local file paths
        run: |
          cd guide
          mdbook build
          cargo run --bin lfp src
      - name: Validate references
        run: bash ci/validate.sh
      - name: Check for broken links
        run: |
          cd guide
          curl -sSLo linkcheck.sh \
            https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
          # Cannot use --all here because of the generated redirect pages aren't available.
          sh linkcheck.sh book
