name: Publish

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag to publish'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  publish-cratesio:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    environment: "publish-crates.io"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag-name }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Upload punktf-lib to crates.io
        uses: actions-rs/cargo@v1
        # The lib crate might fail, when no changes to it where made
        # This `if` makes sure the publishing continues
        continue-on-error: true
        with:
          command: publish
          args: -p punktf-lib
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Upload punktf to crates.io
        uses: actions-rs/cargo@v1
        # The lib crate might fail, when no changes to it where made
        # This `if` makes sure the publishing continues
        if: always()
        with:
          command: publish
          args: -p punktf
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-aur:
    name: Publish to AUR
    runs-on: ubuntu-latest
    environment: "publish-aur"
    steps:
      - name: Update AUR package
        uses: ATiltedTree/create-aur-release@v1
        with:
          package_name: punktf
          package_version: ${{ github.event.inputs.tag-name }}
          commit_username: "Jonas Grawe"
          commit_email: "Shemnei@users.noreply.github.com"
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

  publish-homebrew:
    name: Publish to Homebrew
    runs-on: ubuntu-latest
    environment: "publish-homebrew"
    steps:
      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: punktf
          homebrew-tap: michidk/homebrew-tools
          create-pullrequest: true
          tag-name: ${{ github.event.inputs.tag-name }}
          download-url: "https://github.com/Shemnei/punktf/releases/download/${{ github.event.inputs.tag-name }}/punktf-x86_64-unknown-linux-musl.tar.gz"
        env:
          # PAT needs public_repo and workflow access
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
