name: Reviewdog

on:
  push:
    branches:
      - main
  pull_request:

default:
  run:
    shell: bash

jobs:
  typos:
    name: runner / typos
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run typos with reviewdog
        uses: Shemnei/reviewdog-action-typos@v0
        with:
          reporter: github-check
